kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-release-next-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: pipeline-release-next-pv
  storageClassName: local
  volumeMode: Filesystem

