apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/core/configmaps/
  - ../../base/core/persistentvolumes/
  - ../../base/core/persistentvolumeclaims/
  - ../../base/storage.k8s.io/storageclasses/
  - ../../base/tekton.dev/pipelines/
  - ../../base/tekton.dev/tasks/
namespace: okd-coreos
