kind: PersistentVolume
apiVersion: v1
metadata:
  name: pipeline-release-next-pv
spec:
  capacity:
    storage: 40Gi
  local:
    path: /tmp
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - host-192-168-111-72